### ISSUE TITLE
Could not install with zef

### ISSUE THREAD

**Issue by lizmat** [vrurg/raku-Async-Workers#1]
$ zef install Async::Workers
    ===> Searching for: Async::Workers
    ===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
    ===> Updating p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
    ===> Updated p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
    ===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
    ===> Searching for missing dependencies: AttrX::Mooish
    ===> Testing: AttrX::Mooish:ver<0.6.2>:auth<github:vrurg>
    ===> Testing [OK] for AttrX::Mooish:ver<0.6.2>:auth<github:vrurg>
    ===> Testing: Async::Workers:ver<0.0.1>:auth<github:vrurg>
        # Failed test 'queue reduction count'
        # at t/010-workers.t6 line 57
        # expected: '8'
        #      got: '7'
        # Looks like you failed 1 test of 1
    # Failed test 'Limited queue'
    # at t/010-workers.t6 line 34
    # Looks like you failed 1 test of 3
    ===> Testing [FAIL]: Async::Workers:ver<0.0.1>:auth<github:vrurg>
    Aborting due to test failure: Async::Workers:ver<0.0.1>:auth<github:vrurg> (use --force-test to override)
    LizyPro:rakudo.moar liz$ zef install Async::Workers
    ===> Searching for: Async::Workers
    ===> Searching for missing dependencies: AttrX::Mooish
    ===> Testing: AttrX::Mooish:ver<0.6.2>:auth<github:vrurg>
    ===> Testing [OK] for AttrX::Mooish:ver<0.6.2>:auth<github:vrurg>
    ===> Testing: Async::Workers:ver<0.0.1>:auth<github:vrurg>
    ===> Testing [OK] for Async::Workers:ver<0.0.1>:auth<github:vrurg>
    ===> Installing: AttrX::Mooish:ver<0.6.2>:auth<github:vrurg>
    ===> Installing: Async::Workers:ver<0.0.1>:auth<github:vrurg>
    ===> Install [FAIL] for Async::Workers:ver<0.0.1>:auth<github:vrurg>: ===SORRY!===
    Could not find Async::Msg at line 167 in:
        inst#/Users/liz/Github/rakudo.moar/install/share/perl6/site
        inst#/Users/liz/Github/rakudo.moar/install/share/perl6/vendor
        inst#/Users/liz/Github/rakudo.moar/install/share/perl6
        ap#
        nqp#
        perl5#

    ===SORRY!===
    Could not find Async::Msg at line 167 in:
        inst#/Users/liz/Github/rakudo.moar/install/share/perl6/site
        inst#/Users/liz/Github/rakudo.moar/install/share/perl6/vendor
        inst#/Users/liz/Github/rakudo.moar/install/share/perl6
        ap#
        nqp#
        perl5#

**Comment by vrurg** [comment]
META is fixed.

But the failing test is weird. I can't reproduce it.

**Comment by lizmat** [comment]
the failing test feels like a race condition...

**Comment by vrurg** [comment]
It does. But there shouldn't be any. Hope I catch it eventually.

**Comment by vrurg** [comment]
Ok, thanks @lizmat! There is a race condition after all. What's worse, there seem to be a race condition in the core too:

>`Cannot find method 'find_method_qualified' on object of type Perl6::Metamodel::SubsetHOW`

**Comment by lizmat** [comment]
Would appreciate if you could golf that :-)

**Comment by vrurg** [comment]
It really took me quite some time, but I pinned down the main problem and here is a report: MoarVM/MoarVM#1101. The error message on `cannot find method` is a side-effect of using `AttrX::Mooish` which suffers from a `DESTROY` method not being called for a demolished object.

**Comment by vrurg** [comment]
Seems like it currently installs fine.
